---
project:
  description: DarkPAN::Indexer
  author:
    name: Rob Lauer
    mailto: rclauer@gmail.com
pm-module: DarkPAN::Indexer
min-perl-version: 5.010
dependencies:
  requires: requires
  test-requires: test-requires
  recommends: recommends
  suggests: suggests
path:
  pm-module: lib
  exe-files: bin
  tests: t
extra-files:
  - ChangeLog
  - share:
      - README.md
      - share/Foo-1.0.0.tar.gz
      - share/Foo-1.0.1.tar.gz
  - t/dat:
      - t/dat/Acme-YakiniQ-0.01.tar.gz
resources:
  bugtracker:
    mailto: rclauer@gmail.com
    web: https://github.com/rlauer6/DarkPAN-Indexer/issues
  homepage: https://github.com/rlauer6/DarkPAN-Indexer
  repository:
    type: git
    url: git@github.com:rlauer6/DarkPAN-Indexer.git
    web: https://github.com/rlauer6/DarkPAN-Indexer
